version: 2.1

executors:
  aws:
      docker:
        - image: amazon/aws-sam-cli-build-image-python3.8

workflows:
  lambda-functions:
    jobs:
      - copy:
          #filters:
          #  branches:
          #    only:
          #      - main
          context:
            - login-sandbox

jobs:
  copy:
    executor: aws
    steps:
      - aws-cli-configure
      - checkout
      - package-repo
      - copy-to-s3

commands:
  aws-cli-configure:
    steps:
      - run:
          name: "Configure AWS CLI"
          command: |
            aws configure set default.aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set default.aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

  package-repo:
    steps:
      - run:
          name: "Package Functions"
          command: |
            echo $CIRCLE_SHA1 > gitsha.txt
            zip -r identity-infra-functions.zip .

  copy-to-s3:
    steps:
      - run:
          name: "Copy packages to S3"
          command: |
            aws s3 cp identity-infra-functions.zip s3://$DEPLOY_S3_BUCKET/circleci/identity-infra-functions/$CIRCLE_BRANCH/
