version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: 2.7
    commands:
      - pip3 install --upgrade aws-sam-cli 

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - |
        sam deploy --template-file identity-infra-functions.template.yaml \
          --stack-name $STACK_NAME \
          environment=$ENVIRONMENT \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset
