AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  environment:
    Type: String
    Description: Deployment environment
    Default: "account"

Metadata:
  AWS::ServerlessRepo::Application:
    Name: login-infra-functions
    Description: Demo
    Author: logindotgov
    SpdxLicenseId: CC0-1.0
    HomePageUrl: https://github.com/18f/identity-infra-functions
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/18f/identity-infra-functions
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Application Settings
        Parameters:
          - environment

Description: >
  identity-infra-functions

  Infrastructure functions for login.gov

Globals:
  Function:
    Timeout: 60
    Runtime: python3.8
    Environment:
      Variables:
        ENVIRONMENT_NAME: !Ref environment

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: demo-function/
      Handler: app.lambda_handler
      MemorySize: 128
      AutoPublishAlias: !Ref environment
      Runtime: ruby2.7
      DeploymentPreference:
        Type: AllAtOnce
      Tracing: Active
      Tags:
        environment: !Ref environment

  # AWSRubySDKLayer:
  #   Type: "AWS::Serverless::LayerVersion"
  #   Properties:
  #     LayerName: !Sub 
  #       - ${Environment}-infra-ruby-sdk
  #       - Environment: !Ref environment
  #     Description: AWS Ruby SDK
  #     ContentUri: aws-ruby-sdk
  #     CompatibleRuntimes:
  #       - ruby2.7
  #     RetentionPolicy: Retain
  #   Metadata:
  #     BuildMethod: ruby2.7

  # AWSPythonSDKLayer:
  #   Type: "AWS::Serverless::LayerVersion"
  #   Properties:
  #     LayerName: !Sub 
  #       - ${Environment}-infra-python-sdk
  #       - Environment: !Ref environment
  #     Description: AWS Python SDK
  #     ContentUri: aws-python-sdk
  #     CompatibleRuntimes:
  #       - python3.8
  #     RetentionPolicy: Retain
  #   Metadata:
  #     BuildMethod: python3.8
    
Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  